/** Short labels for emails and summary UI — keep in sync with discovery question ids. */
export const DISCOVERY_QUESTION_LABELS: Record<string, string> = {
  design_style: "Design Style",
  color_palette: "Signature Color",
  inspiration: "Inspiration Gallery",
  typography: "Typography Choice",
  pitch: "One-Sentence Pitch",
  north_star: "The North Star",
  emotional_hook: "Emotional Hook",

  upgrade_platform: "Current Platform",
  upgrade_concern: "Critical Concern",
  upgrade_url: "Domain Status",

  hero_offer: "The Hero Offer",
  pain_point: "The Critical Pain Point",
  transformation: "The Transformation",
  social_proof: "Impressive Social Proof",
  visual_trust: "Visual Trust Assets",
  urgency: "The Buying Urgency",

  anchor_platform: "Anchor Platform",
  lead_magnet: "The Lead Magnet",
  dm_killer: "The DM Killer",
  content_pillars: "Content Pillars",
  ultimate_destination: "Ultimate Destination",
  authority_count: "Authority Count",

  fulfillment_logic: "Fulfillment Logic",
  catalog_size: "Catalog Size",
  market_reach: "Market Reach",
  upsell: "High-Ticket Upsell",
  cart_rescue: "Cart Rescue",
  unboxing_vibe: "Unboxing Vibe",

  core_function: "Core Function",
  revenue_model: "Revenue Model",
  user_hierarchy: "User Hierarchy",
  two_minute_win: "2-Minute Win",
  device_priority: "Device Priority",
  data_bridge: "Data Bridge",

  pay_gateway_node: "Primary Settlement",
  fiscal_sync_type: "Revenue Classification",
  gita_grant_tax: "Tax Optimization",
  multilingual_nodes: "Geographic Expansion",
  multi_filter_priority: "Search Priority",
  calendar_sync_type: "Booking Architecture",
  listing_portal_inventory: "Inventory Control",
  course_tracking_gating: "Learning Retention",
  recurring_bill_strategy: "Retention Strategy",
  chatbot_support_filter: "The Support Filter",
  ai_kb_source: "The Knowledge Source",
  rpa_auto_bottleneck: "Operational Bottleneck",
  hubspot_sync_routing: "Pipeline Routing",
  pro_copy_frequency: "Brand Frequency",
};
