import type { Foundation } from './types';

export const FOUNDATIONS: Foundation[] = [
  {
    id: 'landing',
    name: 'Essential',
    emoji: '✨',
    tagline: 'Your first professional web presence',
    category: 'Base',
    priceGEL: 999,
    deliveryTimeline: '7-10 business days',
    effortEstimate: '~12-15 work hours',
    audienceLabel: 'Perfect for: Solo consultants testing the waters',
    revisionRounds: 1,
    warrantyDays: 30,
    ctaLabel: 'Start My Essential Site',
    ctaHref: '/book-strategy',
    description: 'A clean, mobile-ready landing page built from our curated template collection. Perfect for establishing credibility fast without breaking the bank.',
    concept: 'Template-based launch architecture for fast credibility.',
    strategy: 'Template-based approach with limited customization, designed for quick launch velocity.',
    howItWorks: 'Curated template + your brand assets + focused launch setup.',
    scope: [
      'Design & Structure | Template-based design (3 proven layouts)',
      'Design & Structure | 1-page landing page (max 6 sections)',
      'Design & Structure | Mobile-responsive layout',
      'Design & Structure | Your brand colors, fonts, and images applied',
      'Functionality | Contact form (name, email, message to email)',
      'Functionality | Social media link integration',
      'Functionality | Basic SEO meta tags setup',
      'Functionality | SSL certificate included',
      'Delivery & Ownership | Source code ownership (GitHub transfer)',
      'Delivery & Ownership | Hosting deployment assistance',
      'Delivery & Ownership | Written launch guide (PDF)',
      'Delivery & Ownership | 30-day bug-fix warranty',
      'Delivery & Ownership | 1 revision round included'
    ],
    bestFor: ["Solo consultants", "Early-stage service providers", "Fast-launch projects"],
    roiNote: "Designed to maximize your ad-spend ROI.",
    strategyLabel: "THE CONVERSION TUNNEL",
    recommendedModules: [],
    installmentLabel: "or 3 × 333 ₾/month",
  },
  {
    id: 'cms',
    name: 'Professional',
    emoji: '⭐',
    tagline: 'Custom-designed conversion machine',
    isRecommendedTier: true,
    strategyLabel: "THE INDEPENDENCE PRINCIPLE",
    category: 'Base',
    priceGEL: 2299,
    deliveryTimeline: '10-15 business days',
    effortEstimate: '~24 work hours',
    audienceLabel: 'Perfect for: Serious consultants ready to invest',
    revisionRounds: 2,
    warrantyDays: 90,
    ctaLabel: 'Build My Professional Site',
    ctaHref: '/architect?tier=professional',
    description: "A strategically crafted landing page optimized to turn visitors into leads. Built from scratch for your brand—no templates, no limitations.",
    scope: [
      'Design & Structure | 100% custom design from scratch',
      'Design & Structure | Unlimited sections and content blocks',
      'Design & Structure | Mobile-first responsive approach',
      'Design & Structure | Conversion-optimized layout architecture',
      'Design & Structure | Subtle scroll animations and hover effects',
      'Functionality | Advanced contact form (file uploads, dropdowns)',
      'Functionality | Social proof section (testimonials, logos, video)',
      'Functionality | Google Analytics 4 + event tracking',
      'Functionality | Full SEO suite (schema, OG tags, sitemap)',
      'Functionality | Performance optimization (<2.5s load target)',
      'Functionality | CRM-ready integration prep',
      'Support & Training | Source code ownership + technical docs',
      'Support & Training | 1-hour recorded training session',
      'Support & Training | 90-day comprehensive warranty',
      'Support & Training | 2 revision rounds',
      'Support & Training | 30-day post-launch email support'
    ],
    concept: "Custom conversion architecture for premium client acquisition.",
    strategy: "Template constraints removed. This tier is custom-designed for your brand and conversion goals.",
    howItWorks: 'Research-informed layout + custom UI + conversion instrumentation.',

    bestFor: ["B2B Consultants & Coaches", "Creative & Marketing Agencies", "High-Ticket Service Providers", "Professional Personal Brands"],
    roiNote: "Built for owner-independence and authority.",
    recommendedModules: ['calendar-sync', 'hubspot-sync', 'social-sync', 'local-seo', 'multilingual', 'seo-audit', 'deposit-logic', 'micro-animations', 'extra-page', 'map-marker', 'doc-template'],
    installmentLabel: "or 3 × 767 ₾/month",
  },
  {
    id: 'ecomm',
    name: 'E-Commerce HQ',
    emoji: '💰',
    tagline: 'Georgian e-commerce done right',
    category: 'Base',
    priceGEL: 17999,
    inheritedValue: { id: 'saas', name: "Command Center Core", priceGEL: 4999 },
    deliveryTimeline: '8-10 weeks',
    effortEstimate: '~100 work hours',
    audienceLabel: 'Perfect for: Product-based businesses ready to scale online',
    revisionRounds: 4,
    warrantyDays: 90,
    ctaLabel: 'Build My E-Commerce Empire',
    ctaHref: '/architect?tier=ecommerce-hq',
    description: "Full online store with native Georgian payment integration (TBC/BOG), automated tax reporting to RS.ge, and inventory management. Built to sell while you sleep.",
    concept: "E-commerce infrastructure designed for Georgian payment and tax realities.",
    strategy: "Compliance, conversion, and operational reliability form the core of this storefront architecture.",
    howItWorks: 'Custom storefront + payment rails + fulfillment and order operations.',
    scope: [
      "The \"Buy\" Engine | Architecting a high-speed 'Checkout Tunnel' designed to keep psychological momentum going until payment is confirmed.",
      "Direct Bank Integration | Hooking into TBC, BOG, or Stripe. (Note: Bank approvals take 7-14 days; we guide you through setup)",
      "The Tax Man (RS.ge) | Automated electronic receipts sent to the Revenue Service instantly with every sale",
      "Last Mile Logistics | Setting up local delivery zones or global shipping label logic tailored to your zones",
      "Business Cockpit | Private dashboard for revenue, orders, and document printing in seconds"
    ],
    bestFor: ["Boutique Owners wanting a premium home", "Wine & Jewelry Makers (Global/Local)", "Artisans looking to automate back-office flow"],
    roiNote: "Automates overheads to scale sales flawlessly.",
    recommendedModules: ['micro-animations', 'sms-hub', 'multi-filter', 'recurring-bill', 'compliance-audit', 'rpa-auto', 'extra-page', 'map-marker', 'doc-template']
  },
  {
    id: 'saas',
    name: "Command Center",
    emoji: '🚀',
    tagline: 'Your professional headquarters',
    category: 'Base',
    priceGEL: 4999,
    deliveryTimeline: '25-35 business days',
    effortEstimate: '~50 work hours',
    audienceLabel: 'Perfect for: Established businesses scaling operations',
    revisionRounds: 3,
    warrantyDays: 90,
    ctaLabel: 'Configure My Command Center',
    ctaHref: '/architect?tier=command-center',
    description: "Multi-page website with blog, CMS, lead capture, and content engine. Moves you from 'one-person show' to 'global brand' with systems you control.",
    concept: "Professional headquarters architecture for scaling operations.",
    strategy: "Structured multi-page systems, content operations, and lead visibility in one controllable stack.",
    howItWorks: 'Centralized architecture for automation, sales workflow clarity, and operational control.',
    scope: [
      "Workflow Layer | Custom dashboard logic for pipeline visibility and operational focus.",
      "Automation Hooks | Calendar, CRM, and routing structure for faster response and better conversion.",
      "Scalable System Core | Built for growth phases without re-platforming every few months.",
      "Ownership | Full legal ownership of your infrastructure under Georgian law."
    ],
    bestFor: ["Service teams replacing manual DM operations", "Operators needing clear workflow orchestration", "Brands preparing to scale with structured systems"],
    roiNote: "Built to centralize and scale operations cleanly."
  },
  {
    id: 'upgrade',
    name: 'Legacy Infrastructure Upgrade',
    category: 'Base',
    priceGEL: 0,
    customPriceLabel: "Project-Based Pricing",
    isBespoke: true,
    description: 'Keep the "House" (your design), but replace the "Plumbing and Electricity" (the code). We make your current site safe, fast, and legal.',
    concept: 'If your site was built before 2025, it\'s a business liability. We don\'t guess, and we don\'t "patch" old problems. We perform a deep-cycle technical audit to find the "rot" in your current code and provide a fixed-price roadmap to make your site fast, safe, and 2026-compliant.',
    strategy: 'Old code is a liability. 96% of successful hacks target outdated infrastructure, and a site that takes 3+ seconds to load is losing 40% of its potential sales. We treat your digital presence like real estate—we renovate the core systems to ensure your asset is protected and profitable.',
    scope: [
      "Doctor's Diagnosis | A deep-cycle forensics report uncovering exactly where your old code is leaking data or revenue.",
      "Surgery Roadmap | A transparent, itemized menu of fixes so you see the ROI before we touch a single line of code."
    ],
    howItWorks: 'The Reality Check: Most websites built before 2025 are "Digital Liabilities." They are slow, vulnerable to 2026 bot attacks, and legally non-compliant with the latest data laws. We don\'t just "tinker"—we perform a surgical replacement. You keep your design, but we swap the "Brain" for our high-performance Sentinel engine, instantly turning a risk into a fortress.',
    bestFor: ["Frustrated WordPress/Wix owners tired of slow dashboards", "Established Businesses with sites built before 2025", "Brands that like their current look but hate their current performance", "Companies needing to meet new GITA or Legal compliance standards"],
    lawyerRole: 'Professional legal audit in cooperation with a licensed attorney performing compliance audits on existing data handling, legally certifying protection against Georgian Fine anchors.',
    roiNote: "Eliminates legal risk and fixes revenue leakage.",
    strategicBacking: [
      {
        title: '🛡️ Security Obsolescence (The "Open Door" Effect)',
        fact: '96% of successful website breaches in 2025 targeted sites with outdated third-party dependencies (plugins, themes, or PHP versions).',
        reality: 'If your site was built more than 18 months ago, its defendse were designed to fight 2023-era bots. 2026 automated AI brute-force attacks find "Zero-Day" vulnerabilities fast.',
        cost: 'Professional malware recovery starts at 1,350 GEL, plus crippling Google ranking blacklist recovery time overheads.'
      },
      {
        title: '⚖️ Regulatory Drift (The "Legal Trap")',
        fact: 'Georgia\'s Personal Data Protection Law (2024) updated requirements for user consent, data encryption, and "The Right to be Forgotten."',
        reality: 'Most legacy sites (especially Wix/WP) use "Standard" cookie banners that do NOT meet strict 2026 active consent requirements.',
        cost: 'Non-compliance carries administrative fines of up to 20,000 GEL. Your site isn\'t just slow; it\'s a legal time bomb.'
      },
      {
        title: '📉 Revenue Leakage (The "0.1s Rule")',
        fact: 'Google\'s Core Web Vitals are now the absolute primary organic ranking criteria.',
        reality: 'Legacy themes are often bloated with "Dead CSS" and unoptimized JS anchors bloating paint workloads.',
        cost: 'For every 0.1s delay stat loses 8.4% conversion revenue. Losing standard 10,000 GEL setups "burns" 800 GEL monthly workloads sets.'
      }
    ],
    recommendedModules: ['compliance-audit', 'seo-audit', 'cro-audit', 'api-opt', 'ga4-analytics', 'heatmap']
  }
];
