import type { Foundation } from './types';

export const FOUNDATIONS: Foundation[] = [
  {
    id: 'cms',
    name: 'Professional',
    emoji: '⭐',
    tagline: 'Custom-designed conversion machine',
    isRecommendedTier: false,
    strategyLabel: "THE INDEPENDENCE PRINCIPLE",
    category: 'Base',
    priceGEL: 999,
    deliveryTimeline: '7-10 business days',
    effortEstimate: '~24 work hours',
    audienceLabel: 'Perfect for: Serious consultants ready to invest',
    revisionRounds: 2,
    warrantyDays: 45,
    ctaLabel: 'Build My Professional Site',
    ctaHref: 'https://wa.me/995579723564?text=' + encodeURIComponent('Hi Genezisi! I\'m interested in the Professional package. Can we discuss next steps?'),
    description: "A strategically crafted landing page optimized to turn visitors into leads. Built from scratch for your brand—no templates, no limitations.",
    scope: [
      'Design & Structure | 100% custom design from scratch',
      'Design & Structure | 4 pre-built sections included (client chooses which 4 from: Services, About, Testimonials, Gallery, Video, Booking)',
      'Design & Structure | Additional sections available as add-ons — ₾50 each (Custom ideas welcome)',
      'Design & Structure | Mobile-first responsive approach',
      'Design & Structure | Conversion-optimized layout architecture',
      'Design & Structure | Subtle scroll animations and hover effects',
      'Functionality | Advanced contact form (file uploads, dropdowns)',
      'Functionality | Social proof section (testimonials, logos, video)',
      'Functionality | Google Analytics 4 + event tracking',
      'Functionality | Full SEO suite (schema, OG tags, sitemap)',
      'Functionality | Performance optimization (<2.5s load target)',
      'Functionality | CRM-ready integration prep',
      'Support & Training | Source code ownership + technical docs',
      'Support & Training | 45-day comprehensive warranty',
      'Support & Training | 2 revision rounds',
    ],
    concept: "Custom conversion architecture for premium client acquisition.",
    strategy: "Template constraints removed. This tier is custom-designed for your brand and conversion goals.",
    howItWorks: 'Research-informed layout + custom UI + conversion instrumentation.',
    bestFor: ["B2B Consultants & Coaches", "Creative & Marketing Agencies", "High-Ticket Service Providers", "Professional Personal Brands"],
    roiNote: "Built for owner-independence and authority.",
    recommendedModules: ['calendar-sync', 'hubspot-sync', 'social-sync', 'local-seo', 'multilingual', 'seo-audit', 'deposit-logic', 'micro-animations', 'map-marker', 'doc-template'],
  },
  {
    id: 'saas',
    name: "Command Center",
    emoji: '🚀',
    tagline: 'Your professional headquarters',
    isRecommendedTier: true,
    category: 'Base',
    priceGEL: 1999,
    deliveryTimeline: '10-15 business days',
    effortEstimate: '~50 work hours',
    audienceLabel: 'Perfect for: Established businesses scaling operations',
    revisionRounds: 3,
    warrantyDays: 75,
    ctaLabel: 'Configure My Command Center',
    ctaHref: 'https://wa.me/995579723564?text=' + encodeURIComponent('Hi Genezisi! I\'m interested in the Command Center package (1,999 ₾). Can we discuss next steps?'),
    description: "Multi-page website with blog, CMS, lead capture, and content engine. Home + About + Contact + Blog — you control everything.",
    concept: "Professional headquarters architecture for scaling operations.",
    strategy: "Structured multi-page systems, content operations, and lead visibility in one controllable stack.",
    howItWorks: 'Centralized architecture for automation, sales workflow clarity, and operational control.',
    scope: [
      "4 Pages | Home + About + Contact + 1 of your choice (Blog, Services, Portfolio, etc.)",
      "CMS Dashboard | You publish updates, change prices, add photos — no developer needed",
      "Multi-Language (EN/GE) | Georgian/English bilingual setup is available as an add-on (one language included in base)",
      "Basic Analytics | Google Analytics 4 included — see who visits and what they click",
      "Priority Support | Faster response times than Professional",
      "75-Day Warranty | Full coverage on any bugs or breakages",
      "3 Revision Rounds | More iterations than Professional for complex builds",
      "Full Code Ownership | You own everything — no lock-in"
    ],
    bestFor: ["Service teams replacing manual DM operations", "Operators needing clear workflow orchestration", "Brands preparing to scale with structured systems"],
    roiNote: "Built to centralize and scale operations cleanly.",
    recommendedModules: ['micro-animations', 'sms-hub', 'multi-filter', 'recurring-bill', 'compliance-audit', 'rpa-auto', 'extra-page', 'map-marker', 'doc-template'],
  },
  {
    id: 'ecomm',
    name: 'E-Commerce HQ',
    emoji: '💰',
    tagline: 'Georgian e-commerce done right',
    category: 'Base',
    priceGEL: 3999,
    customPriceLabel: "starting 3,999 ₾",
    deliveryTimeline: '20-30 business days',
    effortEstimate: '~100 work hours',
    audienceLabel: 'Perfect for: Product-based businesses ready to scale online',
    revisionRounds: 4,
    warrantyDays: 100,
    ctaLabel: 'Build My E-Commerce Store',
    ctaHref: 'https://wa.me/995579723564?text=' + encodeURIComponent('Hi Genezisi! I\'m interested in the E-Commerce HQ package (starting 3,999 ₾). Can we discuss next steps?'),
    description: "Full online store with Georgian payment integration options, inventory management, and order operations. Built to help customers buy clearly and confidently.",
    concept: "E-commerce infrastructure designed for Georgian payment and tax realities.",
    strategy: "Compliance, conversion, and operational reliability form the core of this storefront architecture.",
    howItWorks: 'Custom storefront + payment rails + fulfillment and order operations.',
    scope: [
      "5 Pages | Home + Shop + Products + About + Contact",
      "Full CMS Dashboard | You add products, update prices, manage stock — no developer needed",
      "Business Cockpit | Private dashboard: revenue, orders, invoice printing",
      "GA4 + Advanced Conversion Tracking | Included in base",
      "English Only | Multi-language available as add-on (₾150)",
      "Source Code Ownership | No lock-in",
      "100-Day Warranty | Full coverage on any bugs",
      "4 Revision Rounds | ₾150/hour after"
    ],
    bestFor: ["Boutique Owners wanting a premium home", "Wine & Jewelry Makers (Global/Local)", "Artisans looking to automate back-office flow"],
    roiNote: "Automates overheads to scale sales cleanly.",
    recommendedModules: ['bank-integration', 'rs-ge-sync', 'sms-hub', 'recurring-bill', 'extra-page', 'multi-filter'],
  },
  {
    id: 'upgrade',
    name: 'Legacy Infrastructure Upgrade',
    category: 'Base',
    priceGEL: 0,
    customPriceLabel: "Project-Based Pricing",
    isBespoke: true,
    description: 'Keep the current design direction, but replace the weak technical foundation. I audit your current site, identify what is slow, unsafe, outdated, or hard to maintain, then give you a fixed-price roadmap.',
    concept: 'Older websites can become business liabilities: slow load times, outdated dependencies, weak consent flows, and hard-to-maintain code. The upgrade starts with a clear diagnosis before any rebuild work begins.',
    strategy: 'Fix the business risk first: performance, security, data handling, and maintainability. The goal is a safer, faster, easier-to-own website without unnecessary redesign work.',
    scope: [
      "Diagnosis | A technical review of your current website, hosting, dependencies, forms, analytics, SEO basics, and conversion path.",
      "Roadmap | A transparent, itemized fix plan so you understand the priority, cost, and business reason before work begins."
    ],
    howItWorks: 'I review the current setup, document the risks and quick wins, then propose the smallest rebuild or repair plan that will make the site fast, stable, and credible again.',
    bestFor: ["WordPress/Wix owners tired of slow dashboards", "Established businesses with old websites", "Brands that like their current look but need better performance", "Companies that need cleaner privacy, consent, or data-handling flows"],
    lawyerRole: 'If legal compliance questions are involved, the technical audit can be paired with a licensed professional for the legal review.',
    roiNote: "Reduces technical risk and fixes revenue leakage.",
    strategicBacking: [
      {
        title: 'Security & Maintenance Risk',
        fact: 'Outdated plugins, themes, dependencies, and hosting setups are common sources of website incidents.',
        reality: 'If your site is hard to update or built on old tooling, it may become expensive to maintain and easier to break.',
        cost: 'A focused rebuild can be cheaper than repeated emergency fixes, malware cleanup, and lost customer trust.'
      },
      {
        title: 'Data & Consent Risk',
        fact: 'Modern websites should clearly explain what data they collect and how forms, analytics, cookies, and integrations are handled.',
        reality: 'Many older sites have unclear consent flows, unreviewed plugins, and forms that send data through tools the owner no longer understands.',
        cost: 'A clean audit reduces uncertainty and gives you a practical path to safer data handling.'
      },
      {
        title: 'Performance & Conversion Risk',
        fact: 'Slow pages and confusing layouts reduce trust and make paid traffic less efficient.',
        reality: 'Old themes often carry unused scripts, heavy images, and layout choices that make the site feel dated on mobile.',
        cost: 'Improving speed, clarity, and calls-to-action can make the same traffic more valuable.'
      }
    ],
    recommendedModules: ['compliance-audit', 'seo-audit', 'cro-audit', 'api-opt', 'ga4-analytics', 'heatmap'],
  },
];
